name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cc: [gcc, clangcc]
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-get install clang


    - name: Build cpcldr with ${{ matrix.cxx }}
      run: CC=${{ matrix.cc }} make re
